apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iac

bases:
  - ../../base

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  environment: dev

configMapGenerator:
  - name: iac-config
    namespace: iac
    behavior: merge
    literals:
      - APP_ENV=development

images:
  - name: gcr.io/infra-as-code-tek/iac
    newTag: dev
