apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: iac-backend-config
  namespace: {{ .Values.namespace }}
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /api/v1/health
    port: {{ .Values.service.targetPort }}
  connectionDraining:
    drainingTimeoutSec: 60
  timeoutSec: 30
