apiVersion: v1
kind: Service
metadata:
  name: iac-service
  namespace: {{ .Values.namespace }}
  labels:
    app: iac
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "iac-backend-config"}'
spec:
  type: {{ .Values.service.type }}
  selector:
    app: iac
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
