apiVersion: v2
name: github-runners
description: Helm chart for GitHub self-hosted runners on Kubernetes
type: application
version: 1.0.0
appVersion: "2.311.0"

maintainers:
  - name: IAC Team
    email: team@iac.dev

keywords:
  - github
  - runners
  - ci-cd
  - actions
