apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac
  namespace: iac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iac
  template:
    metadata:
      labels:
        app: iac
    spec:
      containers:
      - name: iac
        image: gcr.io/lenny-iac-prd/iac:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "production"
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: iac-config
              key: PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: iac-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: iac-secrets
              key: DB_PASS
        - name: DB_HOST
          value: "127.0.0.1"  # Will use Cloud SQL Proxy
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
