apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iac

bases:
  - ../../base

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  environment: prd

configMapGenerator:
  - name: iac-config
    namespace: iac
    behavior: merge
    literals:
      - APP_ENV=production

images:
  - name: gcr.io/lenny-iac-prd/iac
    newTag: latest
